Add simple documentation for web_fqdn and web_port
kiali/kiali.io pull request #324
Opened 2020-10-30 16:36 UTC by cfcosta

Documentation followup for https://github.com/kiali/kiali/pull/3383.

2020-10-30 19:07 UTC, israel-hdez requested changes
Text is fine, but this is changing 1.25 docs instead of staging.
Additionally, we cannot merge this until the operator is also updated to support `web_port`.

2020-11-03 13:54 UTC, jshaughn approved these changes

2020-11-03 13:55 UTC, merged

2020-11-03 14:15 UTC, cfcosta commented
I was doing the changes on the operator that @israel-hdez requested, @jshaughn.

But we can merge it today and everything should be ok :)

2020-11-03 14:34 UTC, jshaughn commented
> I was doing the changes on the operator that @israel-hdez requested, @jshaughn.

The doc is in staging only and Edgar already approved the content.  So I merged it.  That shouldn't affect the feature merge, I don't think, but either way, the feature work looks near-complete.