added docs for header auth strategy
kiali/kiali.io pull request #340
Opened 2021-01-08 18:50 UTC by mlbiam

for https://github.com/kiali/kiali/issues/3207

2021-01-08 19:16 UTC, jmazzitelli requested changes
minor typos and corrections

2021-01-08 19:16 UTC, jmazzitelli commented on content/documentation/staging/configuration/authentication/_index.adoc
> +* link:{{< relref "header" >}}[header]: requires kiali to run behind a reverse proxy that is responsible for injecting the user's token or a toekn with impersonation.
```suggestion
* link:{{< relref "header" >}}[header]: requires Kiali to run behind a reverse proxy that is responsible for injecting the user's token or a token with impersonation.
```

2021-01-08 19:16 UTC, jmazzitelli commented on content/documentation/staging/configuration/authentication/header.adoc
> +A policy should be put in place to make sure that the only "client" for kiali is
```suggestion
A policy should be put in place to make sure that the only "client" for Kiali is
```

2021-01-08 19:16 UTC, jmazzitelli commented on content/documentation/staging/configuration/authentication/header.adoc
> +kiali.
```suggestion
Kiali.
```

2021-01-08 19:16 UTC, jmazzitelli commented on content/documentation/staging/configuration/authentication/header.adoc
> +The authenticating reverse proxy should inject short lived token in the
```suggestion
The authenticating reverse proxy should inject a short lived token in the 
```

2021-01-08 19:16 UTC, jmazzitelli commented on content/documentation/staging/configuration/authentication/header.adoc
> +that mach the impersonation headers.  Not only do you want to make sure that the
```suggestion
that match the impersonation headers.  Not only do you want to make sure that the
```

2021-01-08 19:16 UTC, jmazzitelli commented on content/documentation/staging/configuration/authentication/header.adoc
> +authenticating proxy can't be over-riden on which user to authenticate, but also
```suggestion
authenticating proxy can't be overriden on which user to authenticate, but also
```

2021-01-11 13:44 UTC, jmazzitelli requested changes
Sorry - missed this one - the number of auth mechanisms has increased.

2021-01-11 13:44 UTC, jmazzitelli commented on content/documentation/staging/configuration/authentication/_index.adoc
>  Kiali supports four authentication mechanisms:
There are now five (no longer four) of them:

```suggestion
Kiali supports five authentication mechanisms:
```

2021-01-11 14:30 UTC, jmazzitelli approved these changes
LGTM

2021-01-11 17:09 UTC, israel-hdez commented on content/documentation/staging/configuration/authentication/header.adoc
> +=== Network Polcies
Fix to typo

```suggestion
=== Network Policies
```

2021-01-11 17:09 UTC, israel-hdez commented on content/documentation/staging/configuration/authentication/header.adoc
> +==== Drop Incomming Impersonation Headers
Another typo

```suggestion
==== Drop Incoming Impersonation Headers
```

2021-01-18 15:09 UTC, merged