Adding GKE private cluster requirement
kiali/kiali.io pull request #347
Opened 2021-02-05 12:19 UTC by xeviknal

related to https://github.com/kiali/kiali/issues/3494
Pretty much based on https://istio.io/latest/docs/setup/platform-setup/gke/

2021-02-05 14:58 UTC, jshaughn requested changes
Thanks @xeviknal, good content.  Just a few changes for staging, that can then be copied down to the older versions.

2021-02-05 14:58 UTC, jshaughn commented on content/documentation/staging/faq/general/google-cloud-private-cluster.adoc
> +Private clusters have higher network restrictions. Kiali needs your cluster to allow `TCP` traffic between the Kubernates API service and the Istio Control Plane namespace in both `8080` and `15000`
Kubernates --> Kubernetes
namespace in both --> namespace, for both the
Features like `Health` and `Envoy Dump` won't be workinig as expected -->  This is required for features such as  `Health` and `Envoy Dump` to work as expected.

2021-02-05 14:58 UTC, jshaughn commented on content/documentation/staging/faq/general/google-cloud-private-cluster.adoc
> +Make sure that the firewalls in you cluster allow the connections mentioned before.
you --> your
before --> above

2021-02-05 14:58 UTC, jshaughn commented on content/documentation/staging/faq/general/google-cloud-private-cluster.adoc
> +Check our section of Google Kubernetes Engine (GKE) Private Clusters requirements in the https://kiali.io/documentation/latest/installation-guide/#_google_cloud_private_cluster_requirements[Installat
our section of --> section
Clusters -> Cluster

2021-02-05 14:58 UTC, jshaughn commented on content/documentation/staging/faq/general/google-cloud-private-cluster.adoc
> +icon:bullhorn[size=1x]{nbsp} Open an https://github.com/kiali/kiali/issues/new/choose[issue, window="_blank"] if you have a private cluster with a different provider than GKE. We'll try to accomodate
accomodate --> accommodate

2021-02-05 14:58 UTC, jshaughn commented on content/documentation/staging/installation-guide/index.adoc
> +Private clusters on Google Cloud have network restrictions. Kiali needs that your cluster give access from the Kubernetes API to the Istio Control Plane namespace in both `8080` and `15000` ports. In
needs that your cluster give access -->  needs your cluster to allow access
namespace in --> namespace, for both the
 In order to do that, update -->  You must update

2021-02-05 15:17 UTC, xeviknal commented
@jshaughn comments approached!
I feel like a school kid who doesn't read his homework before handing it in :sweat:  Thanks for the corrections.
I've changed all the versions that the info applies to.

2021-02-05 15:25 UTC, jshaughn approved these changes
> I feel like a school kid who doesn't read his homework before handing it in

Are you kidding!  You get an 'A' for being able to write so well in a second language.

2021-02-07 10:36 UTC, dex4er commented
Hi. It is worth of mentioning that Istio by itself requires additional ports to be opened: 15017 (Injection and validation service for GCP loadbancer healthcheck) and 15014 (Control plane monitoring for `istioctl x` commands).

2021-02-08 10:21 UTC, xeviknal commented
hi @dex4er,

thanks for commenting. I am checking the [official istio installation page for GKE](https://istio.io/latest/docs/setup/platform-setup/gke/) and they don't mention the same ports as you do. Are those ports new for istio 1.9? I can't see them anywhere.

Anyway, I am going to add the mention to the istio installation for GKE page to be more helpful, as you suggested.

thanks

2021-02-08 10:58 UTC, xeviknal commented on content/documentation/staging/installation-guide/index.adoc
> +icon:bullhorn[size=1x]{nbsp} Istio deployments on private clusters also need extra ports to be opened. Check the https://istio.io/latest/docs/setup/platform-setup/gke/[Istio installation page for GKE
Good Monday @jshaughn ! Your English student has another delivery for you. Do you mind checking it out? :stuck_out_tongue_closed_eyes: Thank you!

2021-02-08 13:36 UTC, dex4er commented
> thanks for commenting. I am checking the [official istio installation page for GKE](https://istio.io/latest/docs/setup/platform-setup/gke/) and they don't mention the same ports as you do. Are those ports new for istio 1.9? I can't see them anywhere.
> 
> Anyway, I am going to add the mention to the istio installation for GKE page to be more helpful, as you suggested.

Istio has incomplete documentation too and then there are some issues in this project:

https://github.com/istio/istio/issues/30661

https://github.com/istio/istio/issues/30646

As you can see, one issue was filled by me personaly.

2021-02-09 13:58 UTC, lucasponce approved these changes

2021-02-11 11:16 UTC, merged