GKE doc manual pick
kiali/kiali.io pull request #363
Opened 2021-04-19 15:58 UTC by israel-hdez

Replicating changes from PR #362 to v1.33 to make
it available to current/latest docs.

2021-04-19 16:05 UTC, israel-hdez commented
It's there: https://deploy-preview-363--kiali.netlify.app/documentation/latest/configuration/authentication/openid/#_using_with_google_cloud_platform_gke_oauth2

2021-04-19 20:06 UTC, jshaughn requested changes
Looks good but needs to be duplicated to staging or it will only ever be present in 1.33.

2021-04-20 18:57 UTC, israel-hdez commented
@jshaughn Changes in staging were done in https://github.com/kiali/kiali.io/pull/362. This is just replicating changes to v1.33 to make the content available in current "latest" docs :-)

2021-04-20 20:26 UTC, jshaughn approved these changes

2021-04-20 20:26 UTC, merged