Add "why ns not in dropdown" section to FAQ
kiali/kiali.io pull request #368
Opened 2021-04-29 19:31 UTC by nrfox

Fixes kiali/kiali#3145

2021-04-29 19:32 UTC, nrfox commented
@lucasponce if you wouldn't mind taking a look at the "cache" section to make sure that's accurate

2021-04-29 20:54 UTC, jshaughn requested changes
@nrfox Adding this to the `/v1.33` content will make it immediately available for users but it will only be in that version going forward.  You also want to duplicate it to `/staging` to ensure it sows up in future versions.

Content looks good, deferring to Lucas for the cache.

2021-04-29 20:54 UTC, jshaughn commented on content/documentation/v1.33/faq/general/why-ns-not-in-dropdown.adoc
> +When deploying Kiali with the Kiali operator, by default some namespaces are https://github.com/kiali/kiali-operator/blob/v1.33/roles/default/kiali-deploy/defaults/main.yml#L24-L28[excluded] from the
Kaili CR -> Kiali CR

2021-04-30 10:04 UTC, lucasponce commented
I'd also link to the description of the CR for details
https://github.com/kiali/kiali-operator/blob/v1.33/deploy/kiali/kiali_cr.yaml#L746

The cache of objects is mostly transparent for the user, but the cache of namespaces it may be visible, in the meaning that if you create or delete a namespace, cache needs to expire to get a fresh data.

That expiration time is shorter than the regular parameters.

In short, I'd add a note with that link for further details, but the description/wording is ok.

2021-04-30 12:31 UTC, nrfox commented
> I'd also link to the description of the CR for details
> https://github.com/kiali/kiali-operator/blob/v1.33/deploy/kiali/kiali_cr.yaml#L746
> 
> The cache of objects is mostly transparent for the user, but the cache of namespaces it may be visible, in the meaning that if you create or delete a namespace, cache needs to expire to get a fresh data.
> 
> That expiration time is shorter than the regular parameters.
> 
> In short, I'd add a note with that link for further details, but the description/wording is ok.

I did not realize there was a separate cache for namespaces. I thought that namespaces shared the same cache as the other kube objects. I'll get that updated. Thanks for taking a look!

2021-04-30 16:46 UTC, jshaughn approved these changes
LGTM

2021-05-03 06:14 UTC, lucasponce approved these changes

2021-05-03 13:12 UTC, merged