New documentation section for certificates information indicators
kiali/kiali.io pull request #407
Opened 2021-08-26 13:07 UTC by leandroberetta

This PR adds a new section in the features page about the feature certificates information indicators.

2021-08-31 12:47 UTC, leandroberetta commented on content/documentation/v1.39/features/index.adoc
> +Kiali v1.40 introduces a new section in the Help menu for viewing certificates used by internal mTLS.
Thanks for your comments!. Version removed, moved to staging.

2021-08-31 13:40 UTC, jmazzitelli commented
To make kiali.io PRs easier to review, you should post the netlify URLs when they are ready so people can click on the links and go directly to the doc pages.

2021-08-31 13:41 UTC, xeviknal approved these changes
LGTM!

2021-08-31 13:42 UTC, jmazzitelli commented
I believe the two netlify links for this PR are:

* https://deploy-preview-407--kiali.netlify.app/documentation/staging/installation-guide/#_updating_permissions
* https://deploy-preview-407--kiali.netlify.app/documentation/staging/features/#_certificates_information_indicators

2021-08-31 13:52 UTC, jmazzitelli requested changes
Just some minor tweeks

2021-08-31 13:52 UTC, jmazzitelli commented on content/documentation/staging/features/index.adoc
> +* Know whether the default CA is used or if there is other CA configured
```suggestion
* Know whether the default CA is used or if there is another CA configured
```

2021-08-31 13:52 UTC, jmazzitelli commented on content/documentation/staging/features/index.adoc
> +The certificates shown depends on how Istio is configured, the following cases are possible:
```suggestion
The certificates shown depends on how Istio is configured. The following cases are possible:
```

2021-08-31 13:52 UTC, jmazzitelli commented on content/documentation/staging/features/index.adoc
> +* Using https://istio.io/latest/docs/tasks/security/cert-management/dns-cert/[DNS certificates, window=_blank], the information shown is got by reading many secrets found in Istio configuration
```suggestion
* Using Istio CA certificates (default), the information shown is from a secret named *istio-ca-secret*
* Using https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/[Plug in CA certificates, window=_blank], the information shown is from a secret named *cacerts*
* Using https://istio.io/latest/docs/tasks/security/cert-management/dns-cert/[DNS certificates, window=_blank], the information shown is from reading many secrets found in Istio configuration
```

2021-08-31 13:52 UTC, jmazzitelli commented on content/documentation/staging/features/index.adoc
> +Note that displaying this configuration requires permissions to read secrets (istio-ca-secret by default, possibly cacerts or any secret configured when using DNS certificates).
```suggestion
Note that displaying this configuration requires permissions to read secrets (*istio-ca-secret* by default, possibly *cacerts* or any secret configured when using DNS certificates). 
```

2021-08-31 13:52 UTC, jmazzitelli commented on content/documentation/staging/installation-guide/index.adoc
> +When installing the operator with OLM there is no way to update the operator permissions after installing it, the solution is to manually update the cluster role used by the operator as follows:
This is contradictory - first it says "there is no way to update the operator permissions after installing it" and then the following instructions tell you how to update the operator permissions after you installed it. :-)

I think we want this to say:

```suggestion
When installing the operator with OLM there is no way to pre-configure the operator permissions prior to installing the operator. The solution is to manually update the cluster role used by the operator as follows:
```

2021-08-31 14:08 UTC, leandroberetta commented
@xeviknal @jmazzitelli thanks for the review. All suggestions committed.

2021-08-31 14:24 UTC, jmazzitelli approved these changes

2021-08-31 14:25 UTC, jmazzitelli commented
Ignore the verification error - looks like redhat.com took too long when netlify was trying to verify a link:
```
  *  External link https://www.redhat.com/en/visualize_and_secure_your_service_mess_with_rh_os_service_mesh failed: got a time out (response code 0)
```

2021-09-05 14:26 UTC, abonas commented
> To make kiali.io PRs easier to review, you should post the netlify URLs when they are ready so people can click on the links and go directly to the doc pages.

aren't those posted as part of the checks when CI is built?
this part:
netlify/kiali/deploy-preview — Deploy Preview ready!

2021-09-05 20:17 UTC, jmazzitelli commented
> aren't those posted as part of the checks when CI is built?
> this part:
> netlify/kiali/deploy-preview — Deploy Preview ready!

Click that link - then try to find the docs that this PR changed :) You will see what I mean.

It's much easier just to post a link directly to the staging page/section where the changes are.

2021-09-07 16:16 UTC, leandroberetta commented
@abonas @jmazzitelli thanks for the advice, I will include the links next time!.

2021-09-08 06:11 UTC, merged