Update secure section of the tutorial with new sidecars generation feature
kiali/kiali.io pull request #420
Opened 2021-10-06 15:15 UTC by leandroberetta

This PR adds new comments and steps to explain the new sidecars generated by "Create traffic policies".

Feature PR: [#2247](https://github.com/kiali/kiali-ui/pull/2247)

2021-10-06 15:24 UTC, leandroberetta commented
To see the new additions:

https://deploy-preview-420--kiali.netlify.app/documentation/staging/tutorial/#01-traffic-policies

2021-10-13 17:03 UTC, lucasponce commented on content/documentation/staging/tutorial/06-secure/01-traffic-policies.adoc
> +Besides authorization policies, sidecars can be created to limit the hosts a given workload can communicate with. This helps to better control traffic and also to reduce the https://istio.io/latest/d
This is style and probably @jshaughn may have better suggestions than me on this.

But I'd start the phrase like:

"Additionally, Istio sidecars can be created to ..."

2021-10-13 17:14 UTC, lucasponce commented on content/documentation/staging/tutorial/06-secure/01-traffic-policies.adoc
> +This information is propagated into the Istio Telemetry and Kiali can use it to define a set of AuthorizationPolicy rules.
--> "a set of AuthorizationPolicy rules and Sidecars" 

And below I'd add

"Sidecars restrict the list of hosts each workload can communicate with using the current traffic" ?

2021-10-13 17:20 UTC, lucasponce commented on content/documentation/staging/tutorial/06-secure/01-traffic-policies.adoc
> +According to https://istio.io/latest/docs/reference/config/networking/sidecar/[Sidecar, window="_blank"] documentation, Istio will program all sidecar proxies in the mesh with the necessary configura
Not sure if it's me but "Istio will program" -> "Istio will configure" sounds perhaps more straightforward/clear ?

2021-10-13 18:56 UTC, jshaughn requested changes
Nothing wrong with the PR but I think actually I want to freeze ay changes to master.  I will add myself as an assignee here, and will work the changes into the docsy branch, which is already updated with other content and will replace master befoer the next release.

2021-10-14 16:43 UTC, jmazzitelli requested changes
We'll want to resubmit this PR once the new docsy website is in place. Putting a block on this PR so it doesn't get merged.

2021-10-14 16:52 UTC, closed without merging

2021-10-14 16:57 UTC, israel-hdez commented
@leandroberetta This was automatically closed when the `master` branch was deleted.
Please, prepare a new PR. The `master` branch no longer exists. You should now target the `staging` branch.

2021-10-14 17:07 UTC, jshaughn commented
@leandroberetta no, don't worry about a new PR.  I will handle it, thanks!