Add Istio environment configuration doc page
kiali/kiali.io pull request #474
Opened 2021-11-11 22:45 UTC by israel-hdez

Related to kiali/kiali#3858

2021-11-11 22:58 UTC, jmazzitelli approved these changes
this looks good

2021-11-12 15:55 UTC, jshaughn requested changes
A couple of minor chnages suggested.  Note that I have been removing the alert titles because the rest of the website does not use them to reinforce the sidebar color.  Titles are reserved for when the information needs to be classified to a certain environment, like `title="OpenShift"`.   This is mainly for readability.  If people think all alerts should have a title, then I'd suggest a PR just for enforcing the new convention, updating all across the website.

2021-11-12 15:55 UTC, jshaughn commented on content/en/docs/Configuration/istio.md
> +title: "Istio environment"
```suggestion
title: "Istio Environment"
```

2021-11-12 15:55 UTC, jshaughn commented on content/en/docs/Configuration/istio.md
> +{{% alert title="Warning" color="warning" %}}
```suggestion
{{% alert color="warning" %}}
```

2021-11-12 15:55 UTC, jshaughn commented on content/en/docs/Configuration/istio.md
> +environment. For more information of this Istio configuration, check the [Istio
```suggestion
environment. For more information on this Istio configuration, check the [Istio
```

2021-11-12 15:55 UTC, jshaughn commented on content/en/docs/Configuration/istio.md
> +{{% alert title="Warning" color="warning" %}}
```suggestion
{{% alert color="warning" %}}
```

2021-11-12 17:38 UTC, israel-hdez commented
@jshaughn All your suggestions are in !

2021-11-12 18:35 UTC, jshaughn approved these changes
LGTM!

2021-11-12 19:00 UTC, merged