Added FAQ line for issue 'Missing root span' in trace details.
kiali/kiali.io pull request #480
Opened 2021-11-16 19:26 UTC by hhovsepy

Fix for issue https://github.com/kiali/kiali/issues/4413

2021-11-16 19:33 UTC, jmazzitelli requested changes
minor corrections requested

2021-11-16 19:33 UTC, jmazzitelli commented on content/en/docs/FAQ/distributed-tracing.md
> +### Why I see "Missing root span" for the root span of some span details on Traces tab?
```suggestion
### Why do I see "Missing root span" for the root span of some span details on Traces tab?
```

2021-11-16 19:33 UTC, jmazzitelli commented on content/en/docs/FAQ/distributed-tracing.md
> +In Traces tab, while clicking on a trace, it shows the details of that trace and information about spans. This details also includes the root span information. But for the traces the traffic of which
```suggestion
In Traces tab, while clicking on a trace, it shows the details of that trace and information about spans. These details also include the root span information. But for the traces for traffic that is not coming from ingress-gateway, the root span information is not available in Jaeger, thus Kiali is displaying "Missing root span" for those traces' details and tooltips in Traces tab and in Graph pages.
```

2021-11-18 07:33 UTC, hhovsepy commented
thank you, changes approached

2021-11-18 09:24 UTC, jmazzitelli commented
@hhovsepy FYI for the future: do not squash-force-push commits after committing changes requested by reviewers. It makes it harder to re-review the PR. We should only have to review the parts that changed since the last review. But because of the squash, there is only a single commit and no one can see what you changed since the last commit when the PR was last reviewed.

2021-11-18 09:25 UTC, jmazzitelli approved these changes
lgtm

2021-11-18 09:26 UTC, hhovsepy commented
> @hhovsepy FYI for the future: do not squash-force-push commits after committing changes requested by reviewers. It makes it harder to re-review the PR. We should only have to review the parts that changed since the last review. But because of the squash, there is only a single commit and no one can see what you changed since the last commit when the PR was last reviewed.

so squash commits after the review is finished, or leave them separately (not a good style) ?

2021-11-18 09:26 UTC, merged

2021-11-18 09:38 UTC, jmazzitelli commented
> so squash commits after the review is finished, or leave them separately (not a good style) ?

During the PR review, just keep the individual commits (do not squash them) - as you continue to work on the PR and submit suggested changes, you should have multiple commits in the PR so people can review the changes without having to review the entire thing again (we can just review the last commit you did - since those will only show the diff since the last review).

AFTER everything is done, and you are ready to merge, THEN you click the "squash-merge" button in the github PR which will then squash commit everything into a single commit with then goes into the master branch.

So you only have multiple commits in your PR branch, but when they get merged into the master branch on the main repo, you end up with a single commit. The multiple commits are only temporary and only in your PR branch in your repo.