Make explicit Kiali's need for Istio's debug http endpoint.
kiali/kiali.io pull request #517
Opened 2022-03-16 20:27 UTC by jshaughn

Fixes https://github.com/kiali/kiali/issues/4798

2022-03-16 21:00 UTC, jmazzitelli requested changes

2022-03-16 21:00 UTC, jmazzitelli commented on content/en/docs/Installation/installation-guide/prerequisites.md
> +For more information, see the [Istio documentation](https://istio.io/latest/docs/ops/best-practices/security/#control-plane) for more information.
duplicate verbiage.
```suggestion
For more information, see the [Istio documentation](https://istio.io/latest/docs/ops/best-practices/security/#control-plane).
```

2022-03-17 03:47 UTC, jmazzitelli approved these changes
lgtm

2022-03-17 07:50 UTC, lucasponce approved these changes

2022-03-17 14:34 UTC, merged