replace delete and redeploy with a deployment rollout restart to tran…
kiali/kiali.io pull request #521
Opened 2022-04-06 21:00 UTC by eitansuez

…sition to sidecar-injected workloads

2022-04-07 07:03 UTC, lucasponce approved these changes
Thanks for submitting a PR!

2022-04-12 15:09 UTC, jmazzitelli commented
this needs a rebase on the latest `staging` branch.

2022-04-12 15:10 UTC, jshaughn requested changes
Thanks for the PR @eitansuez.  See the comments, you can revert the changes to two of the files.  As for the actual suggestion to change the `kubectl`  commands, I'm going to add @lucasponce as a reviewer, he is the tutorial creator.  Also, he is on vacation so you may not see a response until next week.

2022-04-12 15:10 UTC, jshaughn commented on config.toml
> +
You don't need to touch this, it will be handled automatically in the release process.

2022-04-12 15:10 UTC, jshaughn commented on content/en/docs/Configuration/kialis.kiali.io.md
> +      strategy.spinnaker.io/versioned: "false"
Similarly, this file should not change.  It is auto-generated based on the config definition.  The ` make gen-doc` runs at release time.

2022-04-12 15:17 UTC, eitansuez commented on config.toml
> +
will do, i'll revert that merge.

2022-04-12 15:18 UTC, eitansuez commented on config.toml
> +
fyi, lucas has already reviewed and approved the pr.  it seems there's a separate workflow authorization because it's my first PR perhaps?

2022-04-12 15:19 UTC, eitansuez commented on content/en/docs/Configuration/kialis.kiali.io.md
> +      strategy.spinnaker.io/versioned: "false"
reverted.

2022-04-12 15:20 UTC, jmazzitelli commented
yeah, lucas approved. we just need to merge this now.

2022-04-12 15:23 UTC, jshaughn approved these changes
Thanks @eitansuez !  And good luck on your talk at Istiocon!

2022-04-12 15:23 UTC, merged

2022-04-12 15:48 UTC, eitansuez commented
> Thanks @eitansuez ! And good luck on your talk at Istiocon!

Thanks!!