created new section, how to set up development environment
kiali/kiali.io pull request #537
Opened 2022-05-27 12:30 UTC by josunect

I've added a new section about how to set up the development environment, under the Contribution guidelines.
I think that might help, this is just some notes taken with the information provided by the team. 

cc @lucasponce

2022-05-27 13:50 UTC, jmazzitelli reviewed
When submitting a kiali.io PR, it is easier for reviewers if you provide the netlify link to the docs that the PR is changing.

For example, I think this is the netlify link to the docs that this PR is creating - is that correct?

https://deploy-preview-537--kiali.netlify.app/docs/contribution-guidelines/development-environment/

As I look at that, the first thing that comes to mind is all those little proxies that looks complicated to create and manage. But all of that is already done for you in the [hack/run-kiali.sh script](https://github.com/kiali/kiali/blob/master/hack/run-kiali.sh) - I would think this documentation should tell the user just to use that one script rather than manually creating and managing all those individual proxies using those individual proxy_ scripts.

2022-05-27 13:54 UTC, josunect commented
Thanks, @jmazzitelli , I didn't know about that run-kiali script. I will test and send an update. 

That link is correct, that is the new section.

2022-05-31 09:51 UTC, josunect commented
The run_kiali script is much more easy to use, and you don't need to create additional files. 

But, for what I can see, it is also starting the kiali process, that will be also started from the IDE, so you can debug from there. 
So, I just wonder:

- It would be possible to add an option to the run-kiali.sh script, to just run the port forward function? - Or create a separate one
- The proxy also does a port forward from istio, that is missing in the run-kiali script.

2022-05-31 11:55 UTC, jmazzitelli commented
> * It would be possible to add an option to the run-kiali.sh script, to just run the port forward function? - Or create a separate one

Yes. There is an option for that. See: https://github.com/kiali/kiali/blob/master/hack/run-kiali.sh#L138-L145

```
-es|--enable-server
      When 'true', this script will start the server and manage its lifecycle.
      When 'false' this script will do nothing to start or stop the server.
      The purpose of this setting is to allow for this script to work while debugging the server in
      a debugging IDE. When 'false', this script will do everything else except start the server, which
      will be the job of an external tool such as an IDE. When 'false' this script will print out a command
      so you can know what that external tool should execute to start a properly configured server.
```

So if you want to run the server itself from your IDE to use the debugger, run `run-kiali.sh` with the `--enable-server false` option.

2022-05-31 12:01 UTC, jmazzitelli commented
If you have VisualStudio Code and want to run kiali in a debugger, then you need to create a file "launch.json" in your local kiali local repo's .vscode directory (e.g. home/source/kiali/kiali/.vscode/launch.json). The file should look like something like this:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Kiali to use hack script services",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}/kiali.go",
            "cwd": "${env:HOME}/tmp/run-kiali",
            "args": ["-config", "${env:HOME}/tmp/run-kiali/run-kiali-config.yaml"],
            "env": {
                "KUBERNETES_SERVICE_HOST": "127.0.0.1",
                "KUBERNETES_SERVICE_PORT": "8001",
                "LOG_LEVEL": "trace"
            }
        }
    ]
}
```

You then start run-kiali.sh like this:

```
hack/run-kiali.sh --tmp-root-dir $HOME/tmp --enable-server false
```

Notice my tmp directory is `$HOME/tmp` - I think you can use any tmp directory you want.

2022-05-31 12:06 UTC, jmazzitelli commented
> The proxy also does a port forward from istio, that is missing in the run-kiali script.

I thought @lucasponce added that recently? ...

Oh, that was in his PR that he closed. It never got merged. Maybe you can put that back in a separate PR? See this:

https://github.com/kiali/kiali/pull/5061/files#diff-4835d54dd5ef3a768c44727c31447cdc82e8fe4cb7be22858493b38ca2d239c4

There are some plugin options in here we don't need, but just add the istiod-related changes for that proxy

2022-06-01 07:34 UTC, josunect commented
> > The proxy also does a port forward from istio, that is missing in the run-kiali script.
> 
> I thought @lucasponce added that recently? ...
> 
> Oh, that was in his PR that he closed. It never got merged. Maybe you can put that back in a separate PR? See this:
> 
> https://github.com/kiali/kiali/pull/5061/files#diff-4835d54dd5ef3a768c44727c31447cdc82e8fe4cb7be22858493b38ca2d239c4
> 
> There are some plugin options in here we don't need, but just add the istiod-related changes for that proxy

Created PR in kiali.io https://github.com/kiali/kiali/pull/5135

2022-06-01 07:35 UTC, josunect commented
> If you have VisualStudio Code and want to run kiali in a debugger, then you need to create a file "launch.json" in your local kiali local repo's .vscode directory (e.g. home/source/kiali/kiali/.vscode/launch.json). The file should look like something like this:
> 
> ```json
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "Launch Kiali to use hack script services",
>             "type": "go",
>             "request": "launch",
>             "mode": "debug",
>             "program": "${workspaceRoot}/kiali.go",
>             "cwd": "${env:HOME}/tmp/run-kiali",
>             "args": ["-config", "${env:HOME}/tmp/run-kiali/run-kiali-config.yaml"],
>             "env": {
>                 "KUBERNETES_SERVICE_HOST": "127.0.0.1",
>                 "KUBERNETES_SERVICE_PORT": "8001",
>                 "LOG_LEVEL": "trace"
>             }
>         }
>     ]
> }
> ```
> 
> You then start run-kiali.sh like this:
> 
> ```
> hack/run-kiali.sh --tmp-root-dir $HOME/tmp --enable-server false
> ```
> 
> Notice my tmp directory is `$HOME/tmp` - I think you can use any tmp directory you want.

Probably it would be interesting to create a new section for VisualStudio.

2022-06-01 10:43 UTC, josunect commented
I've created https://github.com/kiali/kiali/issues/5136 regarding the failing CI.

2022-06-01 13:02 UTC, jmazzitelli requested changes

2022-06-01 13:02 UTC, jmazzitelli commented on content/en/docs/Contribution-guidelines/development-environment.md
> +- As described in [Arquitecture](/docs/architecture/architecture), we would need to have the Kiali dependencies running in an Openshift or Kubernetes
Fix misspelling, and use "OpenShift" as one word, with uppercase O and S.

```suggestion
- As described in [Architecture](/docs/architecture/architecture), we would need to have the Kiali dependencies running in an OpenShift or Kubernetes
```

2022-06-01 13:02 UTC, jmazzitelli commented on content/en/docs/Contribution-guidelines/development-environment.md
> +### Prerrequisites
fix typo:

```suggestion
### Prerequisites 
```

2022-06-01 13:02 UTC, jmazzitelli commented on content/en/docs/Contribution-guidelines/development-environment.md
> +  - [oc](https://docs.openshift.com/container-platform/4.7/cli_reference/openshift_cli/getting-started-cli.html) or [kubectl](https://kubernetes.io/es/docs/tasks/tools/)
We can update this to refer to the latest version of the doc:

```suggestion
  - [oc](https://docs.openshift.com/container-platform/4.10/cli_reference/openshift_cli/getting-started-cli.html) or [kubectl](https://kubernetes.io/es/docs/tasks/tools/)
```

2022-06-01 13:02 UTC, jmazzitelli commented on content/en/docs/Contribution-guidelines/development-environment.md
> +- Istio and required services are running in Minikube or open shift. To install it following the above schema, it is possible to use the following scripts:
Use the "official" way to mention OpenShift:

```suggestion
- Istio and required services are running in Minikube or OpenShift. To install it following the above schema, it is possible to use the following scripts:
```

2022-06-01 13:02 UTC, jmazzitelli commented on content/en/docs/Contribution-guidelines/development-environment.md
> +
Just get rid of the extra line (yes, this is my OCD being triggered :)

```suggestion
```

2022-06-01 13:02 UTC, jmazzitelli commented on content/en/docs/Contribution-guidelines/development-environment.md
> +In order to forward the requests to the backend propertly, we will need to add the following line in kiali/frontend/package.json:
fix typo:

```suggestion
In order to forward the requests to the backend properly, we will need to add the following line in kiali/frontend/package.json:
```

2022-06-01 13:02 UTC, jmazzitelli commented on content/en/docs/Contribution-guidelines/development-environment.md
> +After running the 3 processes, we should be able to access Kiali GUI in localhost:3000
Provide the URL - makes it more specific (it tells the user what URL scheme (http) to use and provides a link the user can click directly after following the steps).

```suggestion
After running the 3 processes, we should be able to access Kiali GUI at http://localhost:3000
```

2022-06-01 13:02 UTC, jmazzitelli commented on content/en/docs/Contribution-guidelines/development-environment.md
> +This file will be places in ~/kiali/config.yaml, and referenced later by the GO local process.
fix typo, and mention the file in fixed font. Mention "Go" consistently (It is capitalized later on in this doc, so I just make it consistent with that here). Note that the file is placed in `/tmp` not `~` by default, see [here](https://github.com/kiali/kiali/blob/v1.51.0/hack/run-kiali.sh#L86)). You can change this location via the [option](https://github.com/kiali/kiali/blob/v1.51.0/hack/run-kiali.sh#L206-L208) `-trd` but that is not used in the command documented further up in this doc.

```suggestion
The Go process will require a configuration to point to these services and other specific configurations.
This file will be placed in `/tmp/kiali/config.yaml` by the `hack/run-kiali.sh` script, and will be referenced later by the Go local process. 
```

2022-06-01 13:02 UTC, jmazzitelli commented on content/en/docs/Contribution-guidelines/development-environment.md
> +```
I am confused what this file is and why it is documented here. I don't think this is needed. Also, it has a setting that is very specific to a particular setup and not a general location that everyone will have - `static_content_root_directory: /home/userTests/kiali-static-files`. The hack/run-kiali.sh script will set this setting for you and will set it to a value that is valid for the user's environment. In addition, it sets up password auth for Jaeger tracing, but that is not enabled by default in most demo Istio set ups.

Instead, what I think you should do is point out the config template that the run-kiali.sh script will use just as a reference in case the user wants to look at it or need to edit it for a particular test scenario. Here's what I think this should be:

```suggestion
The `hack/run-kiali.sh` will generate the configuration file based on [this template file](https://github.com/kiali/kiali/blob/master/hack/run-kiali-config-template.yaml). You are free to modify this template for your own purposes.
```

2022-06-01 13:02 UTC, jmazzitelli commented on static/files/contribution_guide/config.yaml
> +api:
Remove this file from this PR. I do not think it is needed and in fact some settings look wrong. See my earlier comment regarding commenting on the config file template that hack/run-kiali.sh uses to generate the config file.

2022-08-09 12:35 UTC, jmazzitelli commented on content/en/docs/Contribution-guidelines/development-environment.md
> +./run-kiali.sh -pg 13000:3000 -pp 19090:9090 -app 8080 -es false -iu http://127.0.0.1:15014
just a comment - reading this, it makes it seem as though the user NEEDS those options. I rarely pass any options and it works for me. Perhaps explain what those options do (and mention they are really optional).

2022-08-09 12:36 UTC, jmazzitelli commented on content/en/docs/Contribution-guidelines/development-environment.md
> +./run-kiali.sh -pg 13000:3000 -pp 19090:9090 -app 8080 -es false -iu http://127.0.0.1:15014
Or just say, "It can work without any options. Pass `--help` to see the options it takes"

2022-08-09 12:37 UTC, jmazzitelli approved these changes
let's merge this now... we can update it later.

2022-08-09 13:37 UTC, josunect commented on content/en/docs/Contribution-guidelines/development-environment.md
> +./run-kiali.sh -pg 13000:3000 -pp 19090:9090 -app 8080 -es false -iu http://127.0.0.1:15014
Changes added.

2022-08-09 14:21 UTC, jmazzitelli approved these changes
lgtm

2022-08-09 14:47 UTC, josunect commented
> lgtm

Thanks for the review, @jmazzitelli

2022-08-09 14:49 UTC, merged