Release notes 1.53
kiali/kiali.io pull request #560
Opened 2022-07-19 15:22 UTC by josunect

Release notes for version v. 52 
https://github.com/orgs/kiali/projects/59/

They have been generated using the script proposed in https://github.com/kiali/kiali.io/pull/558

2022-07-19 16:47 UTC, israel-hdez commented
@jmazzitelli would you like to review? I think you are more used to what (and what not) should be included in release notes.

2022-07-19 17:58 UTC, jmazzitelli requested changes
This looks good! thanks @josunect 

The only recommended change is to remove the hack PR -- we typically don't announce changes we make to the hack scripts since those are only relevant to kiali developers.

2022-07-19 17:58 UTC, jmazzitelli commented on content/en/news/release-notes.md
> +* [(hack) how to reduce cpu/memory resources consumed by some istio components](https://github.com/kiali/kiali/issues/5264)
```suggestion
```

2022-07-20 08:52 UTC, josunect commented
Thanks, @jmazzitelli ! Proposed change has been committed.

2022-07-20 12:41 UTC, jmazzitelli approved these changes
lgtm -- we'll fix the htmlproofer error in another pr

2022-07-20 12:41 UTC, merged

2022-07-20 15:18 UTC, israel-hdez commented
@jmazzitelli @josunect I think this needs a backport into `current`, no?

2022-07-20 15:32 UTC, jmazzitelli commented
> @jmazzitelli @josunect I think this needs a backport into `current`, no?

ah, yes.. forgot about that. Right - this went into "staging" but we need it in "current" because it needs to go in the current website content.

@josunect just create a cherry-pick PR that puts this commit over in the "current" branch.

2022-07-21 07:34 UTC, josunect commented
> > @jmazzitelli @josunect I think this needs a backport into `current`, no?
> 
> ah, yes.. forgot about that. Right - this went into "staging" but we also need it in "current" because it needs to go in the current website content.
> 
> @josunect just create a cherry-pick PR that puts this commit over in the "current" branch.

Thanks! Done it in https://github.com/kiali/kiali.io/pull/561