use 'create token' command to generate token
kiali/kiali.io pull request #591
Opened 2022-10-14 23:53 UTC by carlin-q-scott

The secret that was referenced in these instructions did not exist for me. But I had used the `create token` command before to do this same thing for the kubernetes-dashboard, so I figured it would work for kiali, and it did!

2022-10-17 15:59 UTC, israel-hdez commented
@carlin-q-scott Which Kubernetes version are you using?

2022-10-18 00:00 UTC, carlin-q-scott commented
> kubectl version
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.25.0

2022-10-18 13:57 UTC, jmazzitelli commented
Ah yes. The latest versions of k8s no longer create this secret for you in the SA.

We might have to keep the old docs, too, and just mention somethign like "If you are using k8s 1.24+ the secret is no longer generated in the SA itself... blah blah blah".

2022-10-18 19:51 UTC, israel-hdez commented
@carlin-q-scott So, I agree with Mazz that the old docs still apply and you shouldn't replace any text. Just add as a note that for Kubernetes versions 1.24+ the token won't exist by default and it should be created with the command you found.

2022-11-17 14:34 UTC, jshaughn commented
@carlin-q-scott , please update the PR with the feedback above, thanks.

2022-11-17 17:35 UTC, carlin-q-scott commented
@jshaughn @israel-hdez I tried to incorporate your feedback into the PR. Please LMK if it's acceptable.

2022-11-17 17:40 UTC, jmazzitelli commented
here's the netlify link for review: https://deploy-preview-591--kiali.netlify.app/docs/faq/authentication/#how-to-obtain-a-token-when-logging-in-via-token-auth-strategy

2022-11-17 17:48 UTC, jmazzitelli requested changes
some minor things but the content overall looks good

2022-11-17 17:48 UTC, jmazzitelli commented on content/en/docs/FAQ/authentication.md
> +> kubectl -n istio-system create token kiali-service-account
for markdown, you need to use triple-backquotes to format this command properly. So this should be this (ignore the backslashes - I can't figure out how to embed the triple-backquotes inside a suggestion - it should be triple backquotes, then newline, then the kubectl command, then newline, then another triple backquote):

```suggestion
\```
kubectl -n istio-system create token kiali-service-account
\```
```

2022-11-17 17:48 UTC, jmazzitelli commented on content/en/docs/FAQ/authentication.md
> +**For kubernetes v1.24+**
Kubernetes should be capitalized: https://kubernetes.io/docs/contribute/style/style-guide/#kubernetes-io-word-list

```suggestion
**For Kubernetes v1.24+**
```

2022-11-17 17:48 UTC, jmazzitelli commented on content/en/docs/FAQ/authentication.md
> +**For kubernetes prior to v1.24**
Kubernetes should be capitalized. See: https://kubernetes.io/docs/contribute/style/style-guide/#kubernetes-io-word-list

```suggestion
**For Kubernetes prior to v1.24**
```

2022-11-17 22:17 UTC, israel-hdez commented
@carlin-q-scott do you want to commit the other suggestions?

2022-11-17 22:29 UTC, jmazzitelli approved these changes

2022-11-17 22:29 UTC, jmazzitelli commented
I committed the two other changes (needed to capitalize `Kubernetes`). This is ready once it goes green.

2022-11-17 22:36 UTC, merged