Added validations for k8s gateway
kiali/kiali.io pull request #618
Opened 2023-01-11 10:35 UTC by josunect

- Added validations documentation for k8s Gateway (1501, 1502, GWAPI)
- Updated color icon 

REF https://github.com/kiali/kiali/issues/5501 https://github.com/kiali/kiali/pull/5687

2023-01-11 10:50 UTC, hhovsepy approved these changes
lgtm, will wait for Jay's review.

2023-01-11 10:59 UTC, josunect commented
validation is failing, but it looks like https://v1-60.kiali.io is not deployed

2023-01-11 17:28 UTC, jshaughn requested changes

2023-01-11 17:28 UTC, jshaughn commented on content/en/docs/Features/validations.md
> +A k8s Gateway define a point where traffic can be translated to Services within the cluster. This is defined through the listeners or addresses. This validation warns the scenario where there is more
```suggestion
A k8s Gateway defines a point where traffic can be translated to Services, within the cluster. This is defined through listeners or addresses. This validation warns when finding multiple Listener definitions for the same port and host combination, in different k8s Gateways.  In this case the traffic handling can be in conflict.
```

2023-01-11 17:28 UTC, jshaughn commented on content/en/docs/Features/validations.md
> +Remove the duplicate k8s gateway entries or merge the two k8s gateway definitions into a single one.
```suggestion
Remove or merge the duplicate k8s gateway entries.
```

2023-01-11 17:28 UTC, jshaughn commented on content/en/docs/Features/validations.md
> +A k8s Gateway define a point where traffic can be translated to Services within the cluster. This is defined through the listeners or addresses. This validation warns the scenario where there is more
```suggestion
A k8s Gateway defines a point where traffic can be translated to Services within the cluster. This is defined through listeners or addresses. This validation warns when finding more than one address (type and value) in different k8s Gateways, where the traffic handling can be in conflict.
```

2023-01-11 17:28 UTC, jshaughn commented on content/en/docs/Features/validations.md
> +Remove the duplicate k8s gateway entries or merge the two k8s gateway definitions into a single one.
```suggestion
Remove or merge the duplicate k8s gateway entries.
```

2023-01-11 17:28 UTC, jshaughn commented on content/en/docs/Features/validations.md
> +The validations under GWAPI rule are generic and will highlight any invalid status created by the Gateway.
```suggestion
The validations under the GWAPI rule are generic and will highlight any invalid status created by the Gateway.
```

2023-01-12 08:47 UTC, josunect commented
Thanks for your review!

2023-01-12 08:47 UTC, merged