Add release notes for 1.66.2
kiali/kiali.io pull request #679
Opened 2023-07-19 16:23 UTC by nrfox

2023-07-19 16:26 UTC, jmazzitelli requested changes

2023-07-19 16:26 UTC, jmazzitelli commented on content/en/news/release-notes.md
> +## 1.66.2
add 1.66.2 section, leaving 1.66.1 alone.

2023-10-30 13:07 UTC, jshaughn commented
@nrfox I think this PR is obsolete.  Close if you agree.

2024-03-04 15:30 UTC, jshaughn commented
Obsolete

2024-03-04 15:30 UTC, closed without merging