Include alternative to set up cluster tracing tags in multi cluster
kiali/kiali.io pull request #715
Opened 2023-11-06 08:44 UTC by josunect

Include alternative to set up cluster tracing tags in multi cluster without using Telemetry API.

2023-11-16 17:46 UTC, nrfox requested changes

2023-11-16 17:46 UTC, nrfox commented on content/en/docs/Configuration/multi-cluster.md
> +              name: ISTIO_META_CLUSTER_ID
I think the indentation is off here and we should only include what is needed to add the cluster id:

```suggestion
meshConfig:
  defaultConfig:
    tracing:
      custom_tags:
        cluster:
          environment:
            name: ISTIO_META_CLUSTER_ID
```

2023-11-17 13:36 UTC, josunect commented on content/en/docs/Configuration/multi-cluster.md
> +              name: ISTIO_META_CLUSTER_ID
Thanks, @nrfox ! Good point.

2023-11-17 14:28 UTC, nrfox approved these changes

2023-11-17 14:28 UTC, merged