Update Distributed Tracing docs
kiali/kiali.io pull request #727
Opened 2023-12-04 14:41 UTC by josunect

Fixes 
https://github.com/kiali/kiali/issues/6894

- Updated some images in the Tracing page https://deploy-preview-727--kiali.netlify.app/docs/features/tracing/
- Added references to Tempo in the Tracing section (https://deploy-preview-727--kiali.netlify.app/docs/features/tracing/ & https://deploy-preview-727--kiali.netlify.app/docs/architecture/architecture/)
- Update the [Tempo configuration](https://deploy-preview-727--kiali.netlify.app/docs/configuration/p8s-jaeger-grafana/tracing/tempo/)
- Added new page - [Debugging Kiali](https://deploy-preview-727--kiali.netlify.app/docs/configuration/debbuging-kiali/) - to document how to enable the feature to emit traces. I don't know why this is not documented for some particular reason (I was not able to find in the docs) or if this is the best place to add it, but I think it could be useful. Anyway, It will need to be updated after https://github.com/kiali/kiali/issues/6908 is merged.

2023-12-04 17:03 UTC, jmazzitelli requested changes

2023-12-04 17:03 UTC, jmazzitelli commented on content/en/docs/Configuration/debbuging-kiali.md
> +> Jaeger **will be deprecated** in the next release.
This should be more specific because it could lead the reader to think Jaeger support within Kiali will be deprecated. However, I think you mean the only thing being deprecated will be Kiali emitting its own tracing data to Jaeger. Kiali will still be able to consume Jaeger tracing.
```suggestion
{{% alert color="warning" %}}
In the next release, the feature of Kiali emitting tracing data into Jaeger **will be deprecated**.
{{% /alert %}}
```

2023-12-04 17:03 UTC, jmazzitelli commented on content/en/docs/Configuration/debbuging-kiali.md
> +![Kiali traces](/images/documentation/configuration/kiali_traces.png)
Can you get a screen shot of Kiali itself showing the traces?! That would be nice, and show how you can use Kiali to debug Kiali itself.

(BTW: I tried to get a screenshot of it, but I can't get Kiali to start, I'm getting a panic at init time, could just be my misconfiguration, but... I'm seeing this when I try to set this observability section):
```
2023-12-04T17:02:00Z INF Tracing Enabled. Initializing tracer with collector url: http://localhost:3100
panic: context deadline exceeded

goroutine 1 [running]:
github.com/kiali/kiali/observability.InitTracer({0xc0005590b0?, 0x3b?})
	/home/jmazzite/source/kiali/kiali/observability/tracing.go:62 +0x825
```
```

2023-12-05 09:53 UTC, josunect commented on content/en/docs/Configuration/debbuging-kiali.md
> +![Kiali traces](/images/documentation/configuration/kiali_traces.png)
I've added the screenshot, but not sure why isn't building (It looks like an internal error `ERROR 2023/12/05 08:30:30 Failed to get JSON resource "https://api.rss2json.com/v1/api.json?timestamp=283627&rss_url=https://www.youtube.com/feeds/videos.xml?channel_id=UCcm2NzDN_UCZKk2yYmOpc5w": Failed to retrieve remote file: Internal Server Error`)

I've created this issue: https://github.com/kiali/kiali/pull/6917 in order to get the traces emitted by Kiali.

2023-12-05 14:22 UTC, jmazzitelli commented
looks like youtube internal server error caused failure - we just need to restart the builds

2023-12-05 14:26 UTC, jmazzitelli commented
closing and re-opening to restart the builds...

2023-12-05 14:41 UTC, jmazzitelli approved these changes

2023-12-05 14:43 UTC, merged