Internationalization feature docs
kiali/kiali.io pull request #762
Opened 2024-03-06 16:18 UTC by ferhoyos

Part of https://github.com/kiali/kiali/issues/2923

Netlify preview link: https://deploy-preview-762--kiali.netlify.app/docs/features/internationalization/

2024-03-20 18:07 UTC, jmazzitelli requested changes
just some minor fixes. All looks good otherwise.

One thing we might want to have in here: Do we want to ask for community contributions for new languages? We could provide a link to another page that tells people how they can add new language translations which they can then submit as a PR.

2024-03-20 18:07 UTC, jmazzitelli commented on content/en/docs/Features/internationalization.md
> +Kiali is used worldwide and some users prefer to display Kiali in a language that they feel more comfortable than English. For this reason Kiali supports internationalization and it has been translat
```suggestion
Kiali is used worldwide and some users prefer to display Kiali in a language that they feel more comfortable than English. For this reason Kiali supports internationalization, and it has been translated into multiple languages.
```

2024-03-20 18:07 UTC, jmazzitelli commented on content/en/docs/Features/internationalization.md
> +By default language selector is hidden and English is the default language.
```suggestion
By default the language selector is hidden, and English is the default language.
```

2024-03-20 18:07 UTC, jmazzitelli commented on content/en/docs/Features/internationalization.md
> +In order to show the language selector a feature flag must be enabled in Kiali CR configuration:
```suggestion
In order to show the language selector a feature flag must be enabled in the Kiali CR:
```

2024-03-20 18:07 UTC, jmazzitelli commented on content/en/docs/Features/internationalization.md
> +As an example this is how Kiali displays overview page in Chinese language:
```suggestion
As an example this is how Kiali displays the overview page in the Chinese language:
```

2024-03-20 18:08 UTC, jshaughn requested changes
Looks great.  A few minor suggestions.  Also, do we want to add a link to your README developer docs on I18N on github?  (I know that's not merged yet, but it will be).

2024-03-20 18:08 UTC, jshaughn commented on content/en/docs/Features/internationalization.md
> +Kiali is used worldwide and some users prefer to display Kiali in a language that they feel more comfortable than English. For this reason Kiali supports internationalization and it has been translat
```suggestion
Kiali is used worldwide and some users prefer to display Kiali in a language that they are more comfortable with than English. For this reason Kiali supports internationalization and it can be localized into multiple languages.
```

2024-03-20 18:08 UTC, jshaughn commented on content/en/docs/Features/internationalization.md
> +By default language selector is hidden and English is the default language.
```suggestion
By default the language selector is hidden, and English is the default language.
```

2024-03-20 18:08 UTC, jshaughn commented on content/en/docs/Features/internationalization.md
> +In order to show the language selector a feature flag must be enabled in Kiali CR configuration:
```suggestion
In order to show the language selector a feature flag must be enabled in the Kiali CR configuration:
```

2024-03-20 18:08 UTC, jshaughn commented on content/en/docs/Features/internationalization.md
> +| Chinese                                 | zh                                 |
```suggestion
| Chinese                                 | zh                                 |
| English                                 | en                                 |
```

2024-03-20 18:08 UTC, jshaughn commented on content/en/docs/Features/internationalization.md
> +As an example this is how Kiali displays overview page in Chinese language:
```suggestion
As an example, this is how Kiali displays the Overview page in Chinese:
```

2024-03-20 18:13 UTC, jmazzitelli commented on content/en/docs/Features/internationalization.md
> +In order to show the language selector a feature flag must be enabled in Kiali CR configuration:
I made the same suggestion (get off my lawn!) but I removed the word configuration. It doesn't really make sense to say "the Kiali CR configuration." You are enabling it in "the  Kiali CR" which defines the server configuration :)

It's all semantics, I don't care either way :) but for the record I don't ever say "the Kiali CR configuration" --- saying "the Kial CR" suffices.

2024-03-20 18:14 UTC, jmazzitelli commented on content/en/docs/Features/internationalization.md
> +| Chinese                                 | zh                                 |
never, ever write a list that isn't alphabetized... jay will find you :)

2024-03-20 18:15 UTC, jmazzitelli commented on content/en/docs/Features/internationalization.md
> +By default language selector is hidden and English is the default language.
@jshaughn made this identical suggestion

2024-03-20 18:15 UTC, jmazzitelli commented on content/en/docs/Features/internationalization.md
> +As an example this is how Kiali displays overview page in Chinese language:
jay made a similar suggestion - take his.

2024-03-21 07:45 UTC, ferhoyos commented on content/en/docs/Features/internationalization.md
> +| Chinese                                 | zh                                 |
hahaha :-)

2024-03-21 09:02 UTC, ferhoyos commented
Thank you @jshaughn and @jmazzitelli for your feedback! It is good to have English native speakers in the team :-) 

As suggested by you, I have added a link to the frontend developments docs if someone wants to collaborate on the internationalization of Kiali.

2024-03-21 13:09 UTC, jmazzitelli approved these changes

2024-03-21 18:21 UTC, jshaughn approved these changes
LG!

2024-03-21 18:21 UTC, merged