Relnotes v2.0
kiali/kiali.io pull request #829
Opened 2024-10-19 17:42 UTC by jshaughn

2024-10-20 12:44 UTC, jmazzitelli commented
Either include it in this PR or have a separate one with an FAQ that mentions how you can switch back to the old style graph (cytoscape).

Something in here https://kiali.io/docs/faq/graph/ like `How can I switch back to the old style (cytoscape) of the graph?`

2024-10-20 12:50 UTC, jmazzitelli requested changes

2024-10-20 12:50 UTC, jmazzitelli commented on content/en/news/release-notes.md
> +1. There is a breaking change in Kiali's namespace management configuration. To limit the namespaces accessible to Kiali, or made visible to users, iali v2.0 users will configure Discovery Selectors.
```suggestion
1. There is a breaking change in Kiali's namespace management configuration. To limit the namespaces accessible to Kiali, or made visible to users, Kiali v2.0 users will configure Discovery Selectors.
```

2024-10-20 12:50 UTC, jmazzitelli commented on content/en/news/release-notes.md
> +  spec.kiali_feature_flags.ui_defaults.graph.impl: "cy"
I would show this in a yaml block (or you can just wrap in single ticks to make it stand out like `spec.kiali_feature_flags.ui_defaults.graph.impl: "cy"`).
````suggestion
```yaml
spec:
  kiali_feature_flags:
    ui_defaults:
      graph:
        impl: "cy"
```
````

2024-10-20 21:34 UTC, jshaughn commented
@jmazzitelli , I added your FAQ.

2024-10-21 01:22 UTC, jmazzitelli approved these changes

2024-10-21 02:56 UTC, merged